package javaapplication11;

import java.awt.*;
import java.awt.event.WindowEvent;

public class Main_Screen extends javax.swing.JFrame {

    /**
     * Creates new form Main_Screen
     */
    public Main_Screen() {
        initComponents();
    }
    
    private void close() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_FarmerRegistration = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu_Animal = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu_Vaccine = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu_Deworming = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu_AI = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu_Treatment = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu_production = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu_Exit = new javax.swing.JMenu();
        jMenuItem_Logout = new javax.swing.JMenuItem();
        jMenuItem_Exit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Animal Management System");
        setBackground(new java.awt.Color(102, 102, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jMenu_FarmerRegistration.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_FarmerRegistration.setText("Farmer Registration");
        jMenu_FarmerRegistration.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_FarmerRegistration.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jMenu_FarmerRegistration.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu_FarmerRegistrationMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu_FarmerRegistration.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jMenu_FarmerRegistrationMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_FarmerRegistrationMenuSelected(evt);
            }
        });
        jMenu_FarmerRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_FarmerRegistrationMouseClicked(evt);
            }
        });
        jMenu_FarmerRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_FarmerRegistrationActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_FarmerRegistration);

        jMenu1.setText(" | ");
        jMenu1.setEnabled(false);
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu_Animal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_Animal.setText("Animal");
        jMenu_Animal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_Animal.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu_AnimalMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu_Animal.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_AnimalMenuSelected(evt);
            }
        });
        jMenu_Animal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_AnimalMouseClicked(evt);
            }
        });
        jMenu_Animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_AnimalActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Animal);

        jMenu2.setText(" | ");
        jMenu2.setEnabled(false);
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu_Vaccine.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_Vaccine.setText("Vaccine");
        jMenu_Vaccine.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_Vaccine.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu_VaccineMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu_Vaccine.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_VaccineMenuSelected(evt);
            }
        });
        jMenu_Vaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_VaccineMouseClicked(evt);
            }
        });
        jMenu_Vaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_VaccineActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Vaccine);

        jMenu3.setText(" | ");
        jMenu3.setEnabled(false);
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu_Deworming.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_Deworming.setText("Deworming");
        jMenu_Deworming.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_Deworming.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_DewormingMenuSelected(evt);
            }
        });
        jMenu_Deworming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_DewormingMouseClicked(evt);
            }
        });
        jMenu_Deworming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_DewormingActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Deworming);

        jMenu4.setText(" | ");
        jMenu4.setEnabled(false);
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu_AI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu_AI.setText("Artificial Insemination");
        jMenu_AI.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_AI.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_AIMenuSelected(evt);
            }
        });
        jMenu_AI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_AIMouseClicked(evt);
            }
        });
        jMenu_AI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_AIActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_AI);

        jMenu5.setText(" | ");
        jMenu5.setEnabled(false);
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu_Treatment.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu_Treatment.setText("Treatment");
        jMenu_Treatment.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_Treatment.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_TreatmentMenuSelected(evt);
            }
        });
        jMenu_Treatment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_TreatmentMouseClicked(evt);
            }
        });
        jMenu_Treatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_TreatmentActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_Treatment);

        jMenu6.setText(" | ");
        jMenu6.setEnabled(false);
        jMenu6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu_production.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_production.setText("Production");
        jMenu_production.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenu_production.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu_productionMenuSelected(evt);
            }
        });
        jMenu_production.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_productionMouseClicked(evt);
            }
        });
        jMenu_production.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_productionActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_production);

        jMenu7.setText(" | ");
        jMenu7.setEnabled(false);
        jMenu7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu7);

        jMenu_Exit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu_Exit.setText("Exit");
        jMenu_Exit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        jMenuItem_Logout.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuItem_Logout.setText("Logout");
        jMenuItem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LogoutActionPerformed(evt);
            }
        });
        jMenu_Exit.add(jMenuItem_Logout);

        jMenuItem_Exit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jMenuItem_Exit.setText("Exit");
        jMenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ExitActionPerformed(evt);
            }
        });
        jMenu_Exit.add(jMenuItem_Exit);

        jMenuBar1.add(jMenu_Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_FarmerRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_FarmerRegistrationActionPerformed
        
    }//GEN-LAST:event_jMenu_FarmerRegistrationActionPerformed

    private void jMenu_AnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_AnimalActionPerformed
        
    }//GEN-LAST:event_jMenu_AnimalActionPerformed

    private void jMenu_VaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_VaccineActionPerformed
        
    }//GEN-LAST:event_jMenu_VaccineActionPerformed

    private void jMenu_DewormingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_DewormingActionPerformed
        
    }//GEN-LAST:event_jMenu_DewormingActionPerformed

    private void jMenu_AIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_AIActionPerformed

    }//GEN-LAST:event_jMenu_AIActionPerformed

    private void jMenu_TreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_TreatmentActionPerformed

    }//GEN-LAST:event_jMenu_TreatmentActionPerformed

    private void jMenu_productionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_productionActionPerformed

    }//GEN-LAST:event_jMenu_productionActionPerformed

    private void jMenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ExitActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem_ExitActionPerformed

    private void jMenuItem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LogoutActionPerformed
        // Close current session and request fresh login
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenuItem_LogoutActionPerformed

    private void jMenu_productionMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_productionMenuSelected

    }//GEN-LAST:event_jMenu_productionMenuSelected

    private void jMenu_FarmerRegistrationMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_FarmerRegistrationMenuSelected

    }//GEN-LAST:event_jMenu_FarmerRegistrationMenuSelected

    private void jMenu_AnimalMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_AnimalMenuSelected

    }//GEN-LAST:event_jMenu_AnimalMenuSelected

    private void jMenu_VaccineMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_VaccineMenuSelected

    }//GEN-LAST:event_jMenu_VaccineMenuSelected

    private void jMenu_DewormingMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_DewormingMenuSelected

    }//GEN-LAST:event_jMenu_DewormingMenuSelected

    private void jMenu_AIMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_AIMenuSelected

    }//GEN-LAST:event_jMenu_AIMenuSelected

    private void jMenu_TreatmentMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_TreatmentMenuSelected

    }//GEN-LAST:event_jMenu_TreatmentMenuSelected

    private void jMenu_FarmerRegistrationMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu_FarmerRegistrationMenuKeyPressed

    }//GEN-LAST:event_jMenu_FarmerRegistrationMenuKeyPressed

    private void jMenu_FarmerRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_FarmerRegistrationMouseClicked
        // Open Farmer Registration form
        new Screen_1().setVisible(true);
    }//GEN-LAST:event_jMenu_FarmerRegistrationMouseClicked

    private void jMenu_AnimalMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu_AnimalMenuKeyPressed

    }//GEN-LAST:event_jMenu_AnimalMenuKeyPressed

    private void jMenu_VaccineMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu_VaccineMenuKeyPressed

    }//GEN-LAST:event_jMenu_VaccineMenuKeyPressed

    private void jMenu_VaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_VaccineMouseClicked
        // Open Vaccination Monitoring form
        new Screen_3().setVisible(true);
    }//GEN-LAST:event_jMenu_VaccineMouseClicked

    private void jMenu_FarmerRegistrationMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu_FarmerRegistrationMenuDeselected

    }//GEN-LAST:event_jMenu_FarmerRegistrationMenuDeselected

    private void jMenu_AnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_AnimalMouseClicked
        // Open Animal form
        new Screen_2().setVisible(true);
    }//GEN-LAST:event_jMenu_AnimalMouseClicked

    private void jMenu_DewormingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_DewormingMouseClicked
        // Open Deworming Monitoring form
        new Screen_4().setVisible(true);
    }//GEN-LAST:event_jMenu_DewormingMouseClicked

    private void jMenu_AIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_AIMouseClicked
        // Open AI Monitoring form
        new Screen_5().setVisible(true);
    }//GEN-LAST:event_jMenu_AIMouseClicked

    private void jMenu_TreatmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_TreatmentMouseClicked
        // Open Treatment Monitoring form
        new Screen_6().setVisible(true);
    }//GEN-LAST:event_jMenu_TreatmentMouseClicked

    private void jMenu_productionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_productionMouseClicked
        // Open Production Monitoring form
        new Screen_7().setVisible(true);
    }//GEN-LAST:event_jMenu_productionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_Exit;
    private javax.swing.JMenuItem jMenuItem_Logout;
    private javax.swing.JMenu jMenu_AI;
    private javax.swing.JMenu jMenu_Animal;
    private javax.swing.JMenu jMenu_Deworming;
    private javax.swing.JMenu jMenu_Exit;
    private javax.swing.JMenu jMenu_FarmerRegistration;
    private javax.swing.JMenu jMenu_Treatment;
    private javax.swing.JMenu jMenu_Vaccine;
    private javax.swing.JMenu jMenu_production;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
